//! Off-chain E2E integration test: bundle → verify roundtrip.
//!
//! This test loads the phase1a_dag_fixture.json (generated by the Remainder prover),
//! constructs a ProofBundle, and verifies it through the zkml-verifier crate.
//!
//! Run with:
//!   cargo test -p zkml-verifier --test off_chain_e2e -- --ignored
//!
//! The test is #[ignore]d by default because it takes ~5s in release mode.

use zkml_verifier::{verify, ProofBundle};

fn fixture_path() -> String {
    format!(
        "{}/../../contracts/test/fixtures/phase1a_dag_fixture.json",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn load_bundle() -> ProofBundle {
    let path = fixture_path();
    let json = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read fixture at {}: {}", path, e));
    let fixture: serde_json::Value = serde_json::from_str(&json).unwrap();

    ProofBundle {
        proof_hex: fixture["proof_hex"].as_str().unwrap().to_string(),
        gens_hex: fixture["gens_hex"].as_str().unwrap().to_string(),
        public_inputs_hex: fixture
            .get("public_inputs_hex")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string(),
        dag_circuit_description: fixture["dag_circuit_description"].clone(),
        model_hash: Some("0xtest_model_hash".to_string()),
        timestamp: Some(1710000000),
        prover_version: Some("0.1.0-test".to_string()),
        circuit_hash: None,
    }
}

/// Full verification roundtrip: fixture → bundle → verify.
#[test]
#[ignore] // ~5s release, ~60s debug
fn test_offchain_verify_roundtrip() {
    let bundle = load_bundle();

    // Verify
    let result = verify(&bundle).expect("verification should succeed");
    assert!(result.verified, "88-layer XGBoost proof should verify");
    assert_ne!(
        result.circuit_hash, [0u8; 32],
        "circuit hash should be non-zero"
    );
}

/// Bundle metadata survives serialization roundtrip.
#[test]
fn test_bundle_serde_roundtrip() {
    let bundle = load_bundle();

    // Serialize → deserialize
    let json = serde_json::to_string(&bundle).unwrap();
    let decoded: ProofBundle = serde_json::from_str(&json).unwrap();

    assert_eq!(decoded.proof_hex, bundle.proof_hex);
    assert_eq!(decoded.gens_hex, bundle.gens_hex);
    assert_eq!(decoded.model_hash, Some("0xtest_model_hash".to_string()));
    assert_eq!(decoded.timestamp, Some(1710000000));
    assert_eq!(decoded.prover_version, Some("0.1.0-test".to_string()));
}

/// Bundle can be loaded from file path.
#[test]
fn test_bundle_from_file() {
    let path = fixture_path();
    // from_file expects the full ProofBundle format, but fixture is a superset.
    // Test that we can at least parse it as a Value and extract fields.
    let json = std::fs::read_to_string(&path).unwrap();
    let v: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert!(v["proof_hex"].is_string());
    assert!(v["gens_hex"].is_string());
    assert!(v["dag_circuit_description"].is_object());
}

/// Tampered proof should fail verification.
#[test]
#[ignore] // ~5s release
fn test_tampered_proof_fails() {
    let mut bundle = load_bundle();

    // Flip a byte in the middle of the proof
    let mut proof_bytes = hex::decode(
        bundle
            .proof_hex
            .strip_prefix("0x")
            .unwrap_or(&bundle.proof_hex),
    )
    .unwrap();
    let mid = proof_bytes.len() / 2;
    proof_bytes[mid] ^= 0xff;
    bundle.proof_hex = format!("0x{}", hex::encode(&proof_bytes));

    let result = verify(&bundle);
    // Should either return verified=false or an error
    match result {
        Ok(r) => assert!(!r.verified, "tampered proof should not verify"),
        Err(_) => {} // Error is also acceptable
    }
}
