{{- if .Values.privateInput.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldzk.fullname" . }}-private-input
  labels:
    {{- include "worldzk.labels" . | nindent 4 }}
    app.kubernetes.io/component: private-input
spec:
  type: ClusterIP
  selector:
    {{- include "worldzk.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: private-input
  ports:
    - name: http
      port: {{ .Values.privateInput.port }}
      targetPort: http
      protocol: TCP
{{- end }}
