{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worldzk.secretName" . }}
  labels:
    {{- include "worldzk.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.operatorPrivateKey }}
  OPERATOR_PRIVATE_KEY: {{ .Values.secrets.operatorPrivateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.enclavePrivateKey }}
  ENCLAVE_PRIVATE_KEY: {{ .Values.secrets.enclavePrivateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.teeVerifierAddress }}
  TEE_VERIFIER_ADDRESS: {{ .Values.secrets.teeVerifierAddress | b64enc | quote }}
  {{- end }}
{{- end }}
