{{- if .Values.serviceAccount.create }}
{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worldzk.operator.serviceAccountName" . }}
  labels:
    {{- include "worldzk.operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.indexer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worldzk.indexer.serviceAccountName" . }}
  labels:
    {{- include "worldzk.indexer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.verifier.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worldzk.verifier.serviceAccountName" . }}
  labels:
    {{- include "worldzk.verifier.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
