{{- if and .Values.verifier.enabled ((.Values.verifier.autoscaling).enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "worldzk.verifier.fullname" . }}
  labels:
    {{- include "worldzk.verifier.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worldzk.verifier.fullname" . }}
  minReplicas: {{ .Values.verifier.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.verifier.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.verifier.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.verifier.autoscaling.scaleDownStabilizationSeconds }}
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.verifier.autoscaling.scaleUpStabilizationSeconds }}
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
{{- end }}
