#!/usr/bin/env tsx
/**
 * ABI Codegen — reads Foundry build artifacts and generates typed ABI exports.
 *
 * Usage:
 *   npx tsx scripts/generate-abi.ts
 *   npm run generate:abi
 *
 * Reads from: ../../contracts/out/<Contract>.sol/<Contract>.json
 * Writes to:  src/abi/index.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// Contracts to extract ABIs from: [variableName, artifactPath]
const CONTRACTS: [string, string][] = [
  ['teeMLVerifierAbi', 'TEEMLVerifier.sol/TEEMLVerifier.json'],
  ['executionEngineAbi', 'ExecutionEngine.sol/ExecutionEngine.json'],
  ['programRegistryAbi', 'ProgramRegistry.sol/ProgramRegistry.json'],
  ['remainderVerifierAbi', 'RemainderVerifier.sol/RemainderVerifier.json'],
  ['proverRegistryAbi', 'ProverRegistry.sol/ProverRegistry.json'],
  ['proverReputationAbi', 'ProverReputation.sol/ProverReputation.json'],
];

const scriptDir = typeof __dirname !== 'undefined'
  ? __dirname
  : path.dirname(fileURLToPath(import.meta.url));

const CONTRACTS_OUT = path.resolve(scriptDir, '../../../contracts/out');
const OUTPUT_FILE = path.resolve(scriptDir, '../src/abi/index.ts');

function stripInternalType(abi: any[]): any[] {
  return abi.map((item) => {
    const cleaned = { ...item };
    if (cleaned.inputs) {
      cleaned.inputs = cleaned.inputs.map((inp: any) => {
        const { internalType, ...rest } = inp;
        if (rest.components) {
          rest.components = rest.components.map((c: any) => {
            const { internalType: _, ...crest } = c;
            return crest;
          });
        }
        return rest;
      });
    }
    if (cleaned.outputs) {
      cleaned.outputs = cleaned.outputs.map((out: any) => {
        const { internalType, ...rest } = out;
        if (rest.components) {
          rest.components = rest.components.map((c: any) => {
            const { internalType: _, ...crest } = c;
            return crest;
          });
        }
        return rest;
      });
    }
    return cleaned;
  });
}

function main() {
  const missing: string[] = [];
  const exports: string[] = [];

  exports.push('// Auto-generated by scripts/generate-abi.ts — do not edit manually');
  exports.push('// Re-run: npm run generate:abi');
  exports.push('');

  for (const [varName, artifactPath] of CONTRACTS) {
    const fullPath = path.join(CONTRACTS_OUT, artifactPath);
    if (!fs.existsSync(fullPath)) {
      missing.push(artifactPath);
      continue;
    }

    const raw = fs.readFileSync(fullPath, 'utf-8');
    const artifact = JSON.parse(raw);
    const abi = stripInternalType(artifact.abi);

    exports.push(`export const ${varName} = ${JSON.stringify(abi, null, 2)} as const;`);
    exports.push('');
  }

  if (missing.length > 0) {
    console.warn(`Warning: missing artifacts (run 'forge build' first): ${missing.join(', ')}`);
  }

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, exports.join('\n'));
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`Exported ${CONTRACTS.length - missing.length} contract ABIs`);
}

main();
