// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import {PoseidonSponge} from "./PoseidonSponge.sol";
import {SumcheckVerifier} from "./SumcheckVerifier.sol";
import {HyraxVerifier} from "./HyraxVerifier.sol";
import {GKRVerifier} from "./GKRVerifier.sol";

/// @title RemainderVerifier
/// @notice Top-level on-chain verifier for Remainder (GKR+Hyrax) proofs
/// @dev Verifies proofs of ML inference generated by Remainder_CE.
///
///      Verification flow:
///      1. Decode ABI-encoded proof into GKR + Hyrax components
///      2. Replay Fiat-Shamir transcript (Poseidon sponge)
///      3. Verify GKR layer reductions (via SumcheckVerifier)
///      4. Verify Hyrax polynomial commitment openings
///      5. Return true if all checks pass
///
///      Each registered circuit has a fixed description hash that
///      identifies the model structure. The proof must reference
///      a registered circuit.
contract RemainderVerifier {
    // ========================================================================
    // TYPES
    // ========================================================================

    /// @notice Registered circuit configuration
    struct CircuitConfig {
        bytes32 circuitHash; // SHA-256 of circuit description
        GKRVerifier.CircuitDescription description;
        bool active;
        string name; // Human-readable name (e.g., "XGBoost-5feat-10trees")
    }

    // ========================================================================
    // STATE
    // ========================================================================

    /// @notice Admin address
    address public admin;

    /// @notice Registered circuits by hash
    mapping(bytes32 => CircuitConfig) public circuits;

    /// @notice List of registered circuit hashes
    bytes32[] public circuitHashes;

    // ========================================================================
    // EVENTS
    // ========================================================================

    event CircuitRegistered(bytes32 indexed circuitHash, string name);
    event CircuitDeactivated(bytes32 indexed circuitHash);
    event ProofVerified(bytes32 indexed circuitHash, bool valid);
    event AdminTransferred(address indexed oldAdmin, address indexed newAdmin);

    // ========================================================================
    // ERRORS
    // ========================================================================

    error NotAdmin();
    error CircuitNotRegistered();
    error CircuitNotActive();
    error InvalidProofSelector();
    error InvalidProofLength();
    error ProofVerificationFailed();

    // ========================================================================
    // MODIFIERS
    // ========================================================================

    modifier onlyAdmin() {
        if (msg.sender != admin) revert NotAdmin();
        _;
    }

    // ========================================================================
    // CONSTRUCTOR
    // ========================================================================

    constructor(address _admin) {
        admin = _admin;
    }

    // ========================================================================
    // VERIFICATION
    // ========================================================================

    /// @notice Verify a Remainder proof
    /// @param proof ABI-encoded proof data (starts with "REM1" selector)
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param publicInputs Public input values
    /// @return valid Whether the proof is valid
    function verifyProof(bytes calldata proof, bytes32 circuitHash, bytes calldata publicInputs)
        external
        returns (bool valid)
    {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Decode the proof
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);

        // Verify GKR proof
        valid = GKRVerifier.verify(gkrProof, config.description, pubInputs);

        emit ProofVerified(circuitHash, valid);
    }

    /// @notice Verify a proof (reverts on invalid proof — for use by ExecutionEngine)
    /// @param proof ABI-encoded proof data
    /// @param circuitHash Circuit identifier
    /// @param publicInputs Public input values
    function verifyOrRevert(bytes calldata proof, bytes32 circuitHash, bytes calldata publicInputs) external view {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Decode and verify
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);

        bool valid = GKRVerifier.verify(gkrProof, config.description, pubInputs);
        if (!valid) revert ProofVerificationFailed();
    }

    // ========================================================================
    // PROOF DECODING
    // ========================================================================

    /// @notice Decode ABI-encoded proof bytes into GKR proof structure
    /// @param proofData Proof data (after selector)
    /// @param publicInputBytes Raw public input bytes
    /// @return gkrProof Decoded GKR proof
    /// @return pubInputs Decoded public inputs as field elements
    function decodeProof(bytes calldata proofData, bytes calldata publicInputBytes)
        internal
        pure
        returns (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs)
    {
        uint256 offset = 0;

        // Read circuit hash (32 bytes)
        // bytes32 proofCircuitHash = bytes32(proofData[offset:offset + 32]);
        offset += 32;

        // Read number of GKR layers
        uint256 numLayers = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;

        // Decode layer proofs
        gkrProof.layerProofs = new GKRVerifier.LayerProof[](numLayers > 0 ? numLayers - 1 : 0);
        gkrProof.outputValues = new uint256[](0);

        for (uint256 i = 0; i < gkrProof.layerProofs.length; i++) {
            // Read number of sumcheck rounds
            uint256 numRounds = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;

            // Read round polynomials
            SumcheckVerifier.RoundPoly[] memory rounds = new SumcheckVerifier.RoundPoly[](numRounds);
            for (uint256 r = 0; r < numRounds; r++) {
                // Read number of evaluations (degree + 1)
                uint256 numEvals = uint256(bytes32(proofData[offset:offset + 32]));
                offset += 32;

                rounds[r].evals = new uint256[](numEvals);
                for (uint256 e = 0; e < numEvals; e++) {
                    rounds[r].evals[e] = uint256(bytes32(proofData[offset:offset + 32]));
                    offset += 32;
                }
            }

            // Read final evaluation
            uint256 finalEval = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;

            gkrProof.layerProofs[i].sumcheckProof =
                SumcheckVerifier.SumcheckProof({rounds: rounds, finalEval: finalEval});

            // Read claims on previous layer
            uint256 numClaims = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;

            gkrProof.layerProofs[i].claimsOnPrevLayer = new uint256[](numClaims);
            for (uint256 c = 0; c < numClaims; c++) {
                gkrProof.layerProofs[i].claimsOnPrevLayer[c] = uint256(bytes32(proofData[offset:offset + 32]));
                offset += 32;
            }
        }

        // Decode Hyrax evaluation proofs
        uint256 numInputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;

        gkrProof.inputProofs = new HyraxVerifier.EvalProof[](numInputProofs);
        for (uint256 i = 0; i < numInputProofs; i++) {
            // Read number of commitment rows
            uint256 numRows = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;

            gkrProof.inputProofs[i].commitmentRows = new HyraxVerifier.G1Point[](numRows);
            for (uint256 r = 0; r < numRows; r++) {
                gkrProof.inputProofs[i].commitmentRows[r].x = uint256(bytes32(proofData[offset:offset + 32]));
                offset += 32;
                gkrProof.inputProofs[i].commitmentRows[r].y = uint256(bytes32(proofData[offset:offset + 32]));
                offset += 32;
            }

            // Read comD point
            gkrProof.inputProofs[i].comD.x = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;
            gkrProof.inputProofs[i].comD.y = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;

            // Read comZ point
            gkrProof.inputProofs[i].comZ.x = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;
            gkrProof.inputProofs[i].comZ.y = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;
        }

        // Decode public inputs
        uint256 numPubInputs = publicInputBytes.length / 32;
        pubInputs = new uint256[](numPubInputs);
        for (uint256 i = 0; i < numPubInputs; i++) {
            pubInputs[i] = uint256(bytes32(publicInputBytes[i * 32:(i + 1) * 32]));
        }
    }

    // ========================================================================
    // CIRCUIT MANAGEMENT
    // ========================================================================

    /// @notice Register a new circuit configuration
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param numLayers Number of GKR circuit layers
    /// @param layerSizes Size of each layer
    /// @param layerTypes Type of each layer (0=add, 1=mul, 2=const, 3=input)
    /// @param isCommitted Whether each layer has Hyrax commitment
    /// @param name Human-readable circuit name
    function registerCircuit(
        bytes32 circuitHash,
        uint256 numLayers,
        uint256[] calldata layerSizes,
        uint8[] calldata layerTypes,
        bool[] calldata isCommitted,
        string calldata name
    ) external onlyAdmin {
        require(circuits[circuitHash].circuitHash == bytes32(0), "Circuit already registered");
        require(layerSizes.length == numLayers, "Layer sizes length mismatch");
        require(layerTypes.length == numLayers, "Layer types length mismatch");
        require(isCommitted.length == numLayers, "IsCommitted length mismatch");

        GKRVerifier.CircuitDescription memory desc = GKRVerifier.CircuitDescription({
            numLayers: numLayers, layerSizes: layerSizes, layerTypes: layerTypes, isCommitted: isCommitted
        });

        circuits[circuitHash] = CircuitConfig({circuitHash: circuitHash, description: desc, active: true, name: name});

        circuitHashes.push(circuitHash);

        emit CircuitRegistered(circuitHash, name);
    }

    /// @notice Deactivate a circuit
    function deactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = false;
        emit CircuitDeactivated(circuitHash);
    }

    /// @notice Reactivate a circuit
    function reactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = true;
    }

    /// @notice Transfer admin rights
    function transferAdmin(address newAdmin) external onlyAdmin {
        emit AdminTransferred(admin, newAdmin);
        admin = newAdmin;
    }

    // ========================================================================
    // VIEW FUNCTIONS
    // ========================================================================

    /// @notice Check if a circuit is registered and active
    function isCircuitActive(bytes32 circuitHash) external view returns (bool) {
        return circuits[circuitHash].active;
    }

    /// @notice Get all registered circuit hashes
    function getCircuitHashes() external view returns (bytes32[] memory) {
        return circuitHashes;
    }
}
