// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import {PoseidonSponge} from "./PoseidonSponge.sol";
import {HyraxVerifier} from "./HyraxVerifier.sol";
import {GKRVerifier} from "./GKRVerifier.sol";
import {GKRHybridVerifier} from "./GKRHybridVerifier.sol";
import {GKRDAGVerifier} from "./GKRDAGVerifier.sol";

/// @title RemainderVerifier
/// @notice Top-level on-chain verifier for Remainder (GKR+Hyrax) proofs
/// @dev Verifies proofs of ML inference generated by Remainder_CE.
///
///      Verification flow:
///      1. Decode ABI-encoded proof into GKR + Hyrax components
///      2. Replay Fiat-Shamir transcript (Poseidon sponge)
///      3. Verify GKR layer reductions (via SumcheckVerifier)
///      4. Verify Hyrax polynomial commitment openings
///      5. Return true if all checks pass
///
///      Each registered circuit has a fixed description hash that
///      identifies the model structure. The proof must reference
///      a registered circuit.
contract RemainderVerifier {
    // ========================================================================
    // TYPES
    // ========================================================================

    /// @notice Registered circuit configuration
    struct CircuitConfig {
        bytes32 circuitHash; // SHA-256 of circuit description
        GKRVerifier.CircuitDescription description;
        bool active;
        string name; // Human-readable name (e.g., "XGBoost-5feat-10trees")
        bytes32 gensHash; // keccak256 of expected Pedersen generators (0 = skip validation)
    }

    // ========================================================================
    // STATE
    // ========================================================================

    /// @notice Admin address
    address public admin;

    /// @notice Groth16 verifier contract address (for hybrid verification)
    address public groth16Verifier;

    /// @notice Registered circuits by hash
    mapping(bytes32 => CircuitConfig) public circuits;

    /// @notice List of registered circuit hashes
    bytes32[] public circuitHashes;

    /// @notice Per-circuit Groth16 verifier addresses
    mapping(bytes32 => address) public circuitGroth16Verifiers;

    /// @notice Per-circuit Groth16 function selectors (for verifyProof(uint256[8],uint256[N]))
    mapping(bytes32 => bytes4) public circuitGroth16Selectors;

    /// @notice DAG circuit configuration
    struct DAGCircuitConfig {
        bytes32 circuitHash;
        GKRDAGVerifier.DAGCircuitDescription description;
        bool active;
        string name;
        bytes32 gensHash;
    }

    /// @notice Registered DAG circuits by hash
    mapping(bytes32 => DAGCircuitConfig) public dagCircuits;

    // ========================================================================
    // EVENTS
    // ========================================================================

    event CircuitRegistered(bytes32 indexed circuitHash, string name);
    event CircuitDeactivated(bytes32 indexed circuitHash);
    event ProofVerified(bytes32 indexed circuitHash, bool valid);
    event AdminTransferred(address indexed oldAdmin, address indexed newAdmin);

    // ========================================================================
    // ERRORS
    // ========================================================================

    error NotAdmin();
    error CircuitNotRegistered();
    error CircuitNotActive();
    error InvalidProofSelector();
    error InvalidProofLength();
    error ProofVerificationFailed();
    error InvalidGenerators();

    // ========================================================================
    // MODIFIERS
    // ========================================================================

    modifier onlyAdmin() {
        if (msg.sender != admin) revert NotAdmin();
        _;
    }

    // ========================================================================
    // CONSTRUCTOR
    // ========================================================================

    constructor(address _admin) {
        admin = _admin;
    }

    // ========================================================================
    // VERIFICATION
    // ========================================================================

    /// @notice Verify a Remainder proof
    /// @param proof ABI-encoded proof data (starts with "REM1" selector)
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param publicInputs Public input values
    /// @param gensData ABI-encoded Pedersen generators for PODP verification
    /// @return valid Whether the proof is valid
    function verifyProof(
        bytes calldata proof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData
    ) external returns (bool valid) {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Validate generators hash if configured
        if (config.gensHash != bytes32(0) && gensData.length > 0) {
            if (keccak256(gensData) != config.gensHash) revert InvalidGenerators();
        }

        // Decode the proof and generators
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);

        // Set up Fiat-Shamir transcript (matches Remainder's ECTranscript protocol)
        PoseidonSponge.Sponge memory sponge = _setupTranscript(circuitHash, pubInputs, gkrProof);

        // Verify GKR proof with pre-seeded transcript
        valid = GKRVerifier.verify(gkrProof, config.description, pubInputs, gens, sponge);

        emit ProofVerified(circuitHash, valid);
    }

    /// @notice Verify a proof (reverts on invalid proof — for use by ExecutionEngine)
    /// @param proof ABI-encoded proof data
    /// @param circuitHash Circuit identifier
    /// @param publicInputs Public input values
    /// @param gensData ABI-encoded Pedersen generators for PODP verification
    function verifyOrRevert(
        bytes calldata proof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData
    ) external view {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Validate generators hash if configured
        if (config.gensHash != bytes32(0) && gensData.length > 0) {
            if (keccak256(gensData) != config.gensHash) revert InvalidGenerators();
        }

        // Decode, set up transcript, and verify
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);
        PoseidonSponge.Sponge memory sponge = _setupTranscript(circuitHash, pubInputs, gkrProof);

        bool valid = GKRVerifier.verify(gkrProof, config.description, pubInputs, gens, sponge);
        if (!valid) revert ProofVerificationFailed();
    }

    // ========================================================================
    // HYBRID GROTH16 VERIFICATION
    // ========================================================================

    /// @notice BN254 scalar field modulus (Fr)
    uint256 private constant FR_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Verify a Remainder proof using the hybrid Groth16 approach
    /// @dev Flow: decode inner proof → replay transcript → verify Groth16 → EC checks
    /// @param innerProof ABI-encoded inner GKR proof (starts with "REM1" selector)
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param publicInputs Public input values
    /// @param gensData ABI-encoded Pedersen generators
    /// @param groth16Proof Groth16 proof (8 uint256 values: A.x, A.y, B.x1, B.x0, B.y1, B.y0, C.x, C.y)
    /// @param groth16Outputs Groth16 public output values:
    ///        [rlcBeta0, rlcBeta1, zDotJStar0, zDotJStar1, lTensor[0..N], zDotR, mleEval]
    ///        where N = 2 * 2^floor(num_vars/2). For medium config (num_vars=4): 14 values.
    function verifyWithGroth16(
        bytes calldata innerProof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData,
        uint256[8] calldata groth16Proof,
        uint256[] calldata groth16Outputs
    ) external view {
        // Validate circuit registration, proof format, generators, and structure
        _validateHybridInputs(circuitHash, innerProof, gensData);

        // Decode the inner proof and generators
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(innerProof[4:], publicInputs);

        // Set up Fiat-Shamir transcript and replay to collect all challenges
        GKRHybridVerifier.TranscriptChallenges memory challenges;
        {
            PoseidonSponge.Sponge memory sponge = _setupTranscript(circuitHash, pubInputs, gkrProof);
            challenges = GKRHybridVerifier.replayTranscriptAndCollectChallenges(gkrProof, sponge);
        }

        // Parse Groth16 outputs into struct
        GKRHybridVerifier.Groth16Outputs memory outputs;
        {
            uint256 numComputeLayers = gkrProof.layerProofs.length;
            outputs = _parseGroth16Outputs(groth16Outputs, numComputeLayers);
        }

        // Build and verify Groth16 proof
        _verifyGroth16(circuitHash, pubInputs, challenges, groth16Proof, outputs);

        // Verify EC equations using Groth16 outputs
        _verifyECChecks(circuitHash, gkrProof, challenges, outputs, gensData, pubInputs);
    }

    /// @dev Verify EC equations (extracted to avoid stack-too-deep in verifyWithGroth16)
    function _verifyECChecks(
        bytes32 circuitHash,
        GKRVerifier.GKRProof memory gkrProof,
        GKRHybridVerifier.TranscriptChallenges memory challenges,
        GKRHybridVerifier.Groth16Outputs memory outputs,
        bytes calldata gensData,
        uint256[] memory pubInputs
    ) private view {
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);
        GKRVerifier.CircuitDescription memory circuit = circuits[circuitHash].description;
        bool ecValid = GKRHybridVerifier.verifyECChecks(gkrProof, challenges, outputs, gens, circuit, pubInputs);
        if (!ecValid) revert ProofVerificationFailed();
    }

    /// @dev Parse flat groth16Outputs array into Groth16Outputs struct
    /// @param groth16Outputs [rlcBeta[0..N], zDotJStar[0..N], lTensor[...], zDotR, mleEval]
    /// @param numComputeLayers Number of computation layers (N)
    function _parseGroth16Outputs(uint256[] calldata groth16Outputs, uint256 numComputeLayers)
        private
        pure
        returns (GKRHybridVerifier.Groth16Outputs memory outputs)
    {
        // Layout: rlcBeta(N) + zDotJStar(N) + lTensor(?) + zDotR(1) + mleEval(1)
        uint256 minLen = 2 * numComputeLayers + 2; // rlcBeta + zDotJStar + zDotR + mleEval
        require(groth16Outputs.length >= minLen, "Hybrid: groth16 outputs too short");

        uint256[] memory rlcBeta = new uint256[](numComputeLayers);
        uint256[] memory zDotJStar = new uint256[](numComputeLayers);
        for (uint256 i = 0; i < numComputeLayers; i++) {
            rlcBeta[i] = groth16Outputs[i];
        }
        for (uint256 i = 0; i < numComputeLayers; i++) {
            zDotJStar[i] = groth16Outputs[numComputeLayers + i];
        }

        uint256 numLTensor = groth16Outputs.length - 2 * numComputeLayers - 2;
        uint256[] memory lTensor = new uint256[](numLTensor);
        for (uint256 i = 0; i < numLTensor; i++) {
            lTensor[i] = groth16Outputs[2 * numComputeLayers + i];
        }

        outputs = GKRHybridVerifier.Groth16Outputs({
            rlcBeta: rlcBeta,
            zDotJStar: zDotJStar,
            lTensor: lTensor,
            zDotR: groth16Outputs[groth16Outputs.length - 2],
            mleEval: groth16Outputs[groth16Outputs.length - 1]
        });
    }

    /// @dev Validate circuit registration, proof format, generators, and circuit structure
    function _validateHybridInputs(bytes32 circuitHash, bytes calldata innerProof, bytes calldata gensData)
        private
        view
    {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (innerProof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(innerProof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Validate generators hash if configured
        if (config.gensHash != bytes32(0) && gensData.length > 0) {
            if (keccak256(gensData) != config.gensHash) revert InvalidGenerators();
        }

        // Validate circuit structure is compatible with hybrid verifier
        // Requires: input layer + at least 1 computation layer.
        // Input layer may be committed or non-committed; verifyECChecks handles both.
        require(config.description.numLayers >= 2, "Hybrid: need >= 2 layers (input + compute)");
        require(config.description.layerTypes[0] == 3, "Hybrid: layer 0 must be input");
    }

    /// @dev Build Groth16 inputs and verify the proof via raw staticcall
    function _verifyGroth16(
        bytes32 circuitHash,
        uint256[] memory pubInputs,
        GKRHybridVerifier.TranscriptChallenges memory challenges,
        uint256[8] calldata groth16Proof,
        GKRHybridVerifier.Groth16Outputs memory groth16Outputs
    ) private view {
        // Convert circuit hash to Fr pair (same LE 16-byte interpretation as Fq; values < 2^128)
        (uint256 circuitHashFr0, uint256 circuitHashFr1) = _hashToFqPair(circuitHash);

        uint256[] memory groth16Inputs =
            GKRHybridVerifier.buildGroth16Inputs(circuitHashFr0, circuitHashFr1, pubInputs, challenges, groth16Outputs);

        (address verifier, bytes4 selector) = _getCircuitGroth16Verifier(circuitHash);
        _callGroth16Verifier(verifier, selector, groth16Proof, groth16Inputs);
    }

    /// @dev Resolve the Groth16 verifier address and selector for a circuit
    function _getCircuitGroth16Verifier(bytes32 circuitHash) private view returns (address verifier, bytes4 selector) {
        verifier = circuitGroth16Verifiers[circuitHash];
        selector = circuitGroth16Selectors[circuitHash];
        // Fallback to global verifier (backward compat with existing tests)
        if (verifier == address(0)) {
            verifier = groth16Verifier;
            selector = bytes4(keccak256("verifyProof(uint256[8],uint256[70])"));
        }
        require(verifier != address(0), "Groth16 verifier not set");
    }

    /// @dev Call the Groth16 verifier with raw staticcall (inline encoding, no offset/length)
    function _callGroth16Verifier(address verifier, bytes4 selector, uint256[8] calldata proof, uint256[] memory inputs)
        private
        view
    {
        // Copy proof to memory for assembly access (calldata fixed arrays don't support .offset)
        uint256[8] memory proofMem = proof;
        uint256 n = inputs.length;
        // Build calldata: selector(4) + 8 proof words + N input words (all inline, 32 bytes each)
        bytes memory data = new bytes(4 + (8 + n) * 32);
        assembly {
            let ptr := add(data, 32) // skip Solidity length prefix
            // Write selector (4 bytes, left-aligned in word)
            mstore(ptr, shl(224, shr(224, selector)))
            ptr := add(ptr, 4)
            // Copy proof (8 uint256s from memory — fixed array has no length prefix)
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                mstore(ptr, mload(add(proofMem, mul(i, 32))))
                ptr := add(ptr, 32)
            }
            // Copy inputs (N uint256s from memory dynamic array — skip length prefix)
            let inputsPtr := add(inputs, 32)
            for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                mstore(ptr, mload(add(inputsPtr, mul(i, 32))))
                ptr := add(ptr, 32)
            }
        }
        (bool success, bytes memory returnData) = verifier.staticcall(data);
        if (!success) {
            if (returnData.length > 0) {
                assembly {
                    revert(add(returnData, 32), mload(returnData))
                }
            }
            revert("Groth16 verification failed");
        }
    }

    /// @dev Compute the selector for verifyProof(uint256[8],uint256[N])
    function _computeGroth16Selector(uint256 n) private pure returns (bytes4) {
        return bytes4(keccak256(abi.encodePacked("verifyProof(uint256[8],uint256[", _uintToString(n), "])")));
    }

    /// @dev Convert uint to string for selector computation
    function _uintToString(uint256 value) private pure returns (string memory) {
        if (value == 0) return "0";
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits--;
            buffer[digits] = bytes1(uint8(48 + value % 10));
            value /= 10;
        }
        return string(buffer);
    }

    /// @notice Public wrapper for transcript replay (for testing)
    function replayTranscriptPublic(bytes calldata innerProof, bytes32 circuitHash, bytes calldata publicInputs)
        external
        view
        returns (uint256[] memory outputChallenges, uint256 claimAggCoeff, uint256 interLayerCoeff)
    {
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(innerProof[4:], publicInputs);
        PoseidonSponge.Sponge memory sponge = _setupTranscript(circuitHash, pubInputs, gkrProof);

        GKRHybridVerifier.TranscriptChallenges memory challenges =
            GKRHybridVerifier.replayTranscriptAndCollectChallenges(gkrProof, sponge);

        outputChallenges = challenges.outputChallenges;
        claimAggCoeff = challenges.claimAggCoeff;
        interLayerCoeff = challenges.interLayerCoeffs.length > 0 ? challenges.interLayerCoeffs[0] : 0;
    }

    // ========================================================================
    // PROOF DECODING
    // ========================================================================

    /// @notice Decode proof and return top-level counts (for testing)
    function decodeProofCounts(bytes calldata proofData, bytes calldata publicInputBytes)
        external
        pure
        returns (uint256 numLayerProofs, uint256 numInputProofs, uint256 numPubInputs)
    {
        (GKRVerifier.GKRProof memory proof, uint256[] memory pubInputs) = decodeProof(proofData, publicInputBytes);
        numLayerProofs = proof.layerProofs.length;
        numInputProofs = proof.inputProofs.length;
        numPubInputs = pubInputs.length;
    }

    /// @notice Decode proof with full structure (for testing)
    function decodeProofCounted(bytes calldata proofData, bytes calldata publicInputBytes)
        external
        pure
        returns (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs)
    {
        return decodeProof(proofData, publicInputBytes);
    }

    /// @notice Public wrapper for _setupTranscript (for testing)
    function setupTranscriptPublic(
        bytes32 circuitHash,
        uint256[] memory pubInputs,
        GKRVerifier.GKRProof memory gkrProof
    ) external view returns (PoseidonSponge.Sponge memory) {
        return _setupTranscript(circuitHash, pubInputs, gkrProof);
    }

    /// @notice Decode proof and return per-layer structure (for testing)
    function decodeLayerDetail(bytes calldata proofData, bytes calldata publicInputBytes, uint256 layerIdx)
        external
        pure
        returns (uint256 numMessages, uint256 numCommits, uint256 numPops)
    {
        (GKRVerifier.GKRProof memory proof,) = decodeProof(proofData, publicInputBytes);
        require(layerIdx < proof.layerProofs.length, "layer index out of bounds");
        numMessages = proof.layerProofs[layerIdx].sumcheckProof.messages.length;
        numCommits = proof.layerProofs[layerIdx].commitments.length;
        numPops = proof.layerProofs[layerIdx].pops.length;
    }

    /// @notice Decode ABI-encoded proof bytes into committed GKR proof structure
    /// @param proofData Proof data (after selector)
    /// @param publicInputBytes Raw public input bytes
    /// @return gkrProof Decoded GKR proof (committed sumcheck format)
    /// @return pubInputs Decoded public inputs as field elements
    function decodeProof(bytes calldata proofData, bytes calldata publicInputBytes)
        internal
        pure
        returns (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs)
    {
        (uint256 offset,) = _decodeProofCommon(proofData, gkrProof);

        // Decode Hyrax input proofs (first eval proof only)
        uint256 numInputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        gkrProof.inputProofs = new HyraxVerifier.EvalProof[](numInputProofs);
        for (uint256 i = 0; i < numInputProofs; i++) {
            offset = _decodeInputProof(proofData, offset, gkrProof.inputProofs[i]);
        }

        pubInputs = _decodePublicInputs(publicInputBytes);
    }

    /// @notice Decode proof with all eval proofs for DAG verification.
    function decodeProofForDAG(bytes calldata proofData, bytes calldata publicInputBytes)
        internal
        pure
        returns (
            GKRVerifier.GKRProof memory gkrProof,
            uint256[] memory pubInputs,
            GKRDAGVerifier.DAGInputLayerProof[] memory dagInputProofs,
            GKRDAGVerifier.PublicValueClaim[] memory publicValueClaims
        )
    {
        (uint256 offset, uint256 pubClaimsOffset) = _decodeProofCommon(proofData, gkrProof);

        // Decode public value claims (Pedersen openings for public input atoms)
        publicValueClaims = _decodePublicValueClaims(proofData, pubClaimsOffset);

        // Decode all eval proofs per input layer
        uint256 numInputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        dagInputProofs = new GKRDAGVerifier.DAGInputLayerProof[](numInputProofs);
        gkrProof.inputProofs = new HyraxVerifier.EvalProof[](0);
        for (uint256 i = 0; i < numInputProofs; i++) {
            offset = _decodeDAGInputLayerProof(proofData, offset, dagInputProofs[i]);
        }

        pubInputs = _decodePublicInputs(publicInputBytes);
    }

    /// @notice Decode proof sections shared between regular and DAG modes.
    /// @return offset The byte offset where input proofs begin
    /// @return pubClaimsOffset The byte offset where public value claims start (for DAG decoding)
    function _decodeProofCommon(bytes calldata proofData, GKRVerifier.GKRProof memory gkrProof)
        private
        pure
        returns (uint256 offset, uint256 pubClaimsOffset)
    {
        // Skip circuit hash (32 bytes)
        offset = 32;

        // Skip public inputs section (decoded separately from publicInputBytes)
        uint256 numPubInputSections = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numPubInputSections; i++) {
            uint256 cnt = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32 + cnt * 32;
        }

        // Decode output layer proofs (claim commitment G1 points from prover)
        uint256 numOutputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        gkrProof.outputValues = new uint256[](0);
        gkrProof.outputClaimCommitments = new HyraxVerifier.G1Point[](numOutputProofs);
        for (uint256 i = 0; i < numOutputProofs; i++) {
            gkrProof.outputClaimCommitments[i].x = uint256(bytes32(proofData[offset:offset + 32]));
            gkrProof.outputClaimCommitments[i].y = uint256(bytes32(proofData[offset + 32:offset + 64]));
            offset += 64;
        }

        // Decode committed layer proofs
        uint256 numLayerProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        gkrProof.layerProofs = new GKRVerifier.CommittedLayerProof[](numLayerProofs);
        for (uint256 i = 0; i < numLayerProofs; i++) {
            offset = _decodeCommittedLayerProof(proofData, offset, gkrProof.layerProofs[i]);
        }

        // Skip Fiat-Shamir claims section
        uint256 numFsClaims = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numFsClaims; i++) {
            offset = _skipClaim(proofData, offset);
        }

        // Save offset for public value claims (DAG mode will decode these)
        pubClaimsOffset = offset;

        // Skip public value claims section
        uint256 numPubClaims = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numPubClaims; i++) {
            offset = _skipClaim(proofData, offset);
        }
    }

    /// @notice Decode public inputs from separate calldata bytes.
    function _decodePublicInputs(bytes calldata publicInputBytes)
        private
        pure
        returns (uint256[] memory pubInputs)
    {
        uint256 numPubInputs = publicInputBytes.length / 32;
        pubInputs = new uint256[](numPubInputs);
        for (uint256 i = 0; i < numPubInputs; i++) {
            pubInputs[i] = uint256(bytes32(publicInputBytes[i * 32:(i + 1) * 32]));
        }
    }

    /// @notice Decode the proof-embedded public inputs (MLE data for non-committed input layers).
    /// @dev The Rust prover absorbs these values into the transcript. They are stored in the proof
    ///      binary as: numSections, then per section: numElements + Fr values.
    ///      This must be used for transcript setup to match the prover's Fiat-Shamir state.
    function _decodeEmbeddedPublicInputs(bytes calldata proofData)
        internal
        pure
        returns (uint256[] memory embeddedPubInputs)
    {
        // Skip circuit hash (32 bytes)
        uint256 offset = 32;

        // Read public inputs sections
        uint256 numSections = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;

        // First pass: count total elements
        uint256 totalElements = 0;
        uint256 savedOffset = offset;
        for (uint256 i = 0; i < numSections; i++) {
            uint256 cnt = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32 + cnt * 32;
            totalElements += cnt;
        }

        // Second pass: extract elements
        embeddedPubInputs = new uint256[](totalElements);
        offset = savedOffset;
        uint256 idx = 0;
        for (uint256 i = 0; i < numSections; i++) {
            uint256 cnt = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32;
            for (uint256 j = 0; j < cnt; j++) {
                embeddedPubInputs[idx++] = uint256(bytes32(proofData[offset:offset + 32]));
                offset += 32;
            }
        }
    }

    /// @dev Decode a single committed layer proof from proof bytes
    function _decodeCommittedLayerProof(
        bytes calldata data,
        uint256 offset,
        GKRVerifier.CommittedLayerProof memory layerProof
    ) private pure returns (uint256) {
        // ProofOfSumcheck: sum (G1)
        layerProof.sumcheckProof.sum.x = uint256(bytes32(data[offset:offset + 32]));
        layerProof.sumcheckProof.sum.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        // ProofOfSumcheck: messages (G1[])
        uint256 numMessages = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.sumcheckProof.messages = new HyraxVerifier.G1Point[](numMessages);
        for (uint256 j = 0; j < numMessages; j++) {
            layerProof.sumcheckProof.messages[j].x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.sumcheckProof.messages[j].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // ProofOfSumcheck: PODP
        offset = _decodePODP(data, offset, layerProof.sumcheckProof.podp);

        // Post-sumcheck commitments (G1[])
        uint256 numCommits = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.commitments = new HyraxVerifier.G1Point[](numCommits);
        for (uint256 j = 0; j < numCommits; j++) {
            layerProof.commitments[j].x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.commitments[j].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // ProofOfProduct entries
        uint256 numPops = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.pops = new HyraxVerifier.ProofOfProduct[](numPops);
        for (uint256 j = 0; j < numPops; j++) {
            // 3 G1 points: alpha, beta, delta
            layerProof.pops[j].alpha.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].alpha.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            layerProof.pops[j].beta.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].beta.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            layerProof.pops[j].delta.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].delta.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            // 5 scalars: z1..z5
            layerProof.pops[j].z1 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z2 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z3 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z4 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z5 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
        }

        // Skip claim aggregation (optional)
        uint256 hasAgg = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        if (hasAgg == 1) {
            // Skip coefficients
            uint256 numCoeffs = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numCoeffs * 64;
            // Skip openings
            uint256 numOpenings = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numOpenings * (64 + 64);
            // Skip equality proofs
            uint256 numEq = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numEq * (64 + 32);
        }

        return offset;
    }

    /// @dev Decode a PODP proof from proof bytes
    function _decodePODP(bytes calldata data, uint256 offset, HyraxVerifier.PODPProof memory podp)
        private
        pure
        returns (uint256)
    {
        podp.commitD.x = uint256(bytes32(data[offset:offset + 32]));
        podp.commitD.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        podp.commitDDotA.x = uint256(bytes32(data[offset:offset + 32]));
        podp.commitDDotA.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        uint256 numZ = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        podp.zVector = new uint256[](numZ);
        for (uint256 i = 0; i < numZ; i++) {
            podp.zVector[i] = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
        }

        podp.zDelta = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        podp.zBeta = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;

        return offset;
    }

    /// @dev Decode a Hyrax input proof (commitment rows + PODP + comEval)
    function _decodeInputProof(bytes calldata data, uint256 offset, HyraxVerifier.EvalProof memory proof)
        private
        pure
        returns (uint256)
    {
        // Commitment rows
        uint256 numRows = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        proof.commitmentRows = new HyraxVerifier.G1Point[](numRows);
        for (uint256 r = 0; r < numRows; r++) {
            proof.commitmentRows[r].x = uint256(bytes32(data[offset:offset + 32]));
            proof.commitmentRows[r].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // Evaluation proofs
        uint256 numEvals = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;

        if (numEvals > 0) {
            offset = _decodePODP(data, offset, proof.podp);
            // commitmentToEvaluation
            proof.comEval.x = uint256(bytes32(data[offset:offset + 32]));
            proof.comEval.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // Skip additional eval proofs
        for (uint256 e = 1; e < numEvals; e++) {
            offset += 128; // commitD + commitDDotA
            uint256 skipZ = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + skipZ * 32 + 64; // z_vector + z_delta + z_beta
            offset += 64; // comEval
        }

        return offset;
    }

    /// @dev Decode a single DAG input layer proof with all eval proofs.
    function _decodeDAGInputLayerProof(
        bytes calldata data,
        uint256 offset,
        GKRDAGVerifier.DAGInputLayerProof memory proof
    ) private pure returns (uint256) {
        // Commitment rows (shared)
        uint256 numRows = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        proof.commitmentRows = new HyraxVerifier.G1Point[](numRows);
        for (uint256 r = 0; r < numRows; r++) {
            proof.commitmentRows[r].x = uint256(bytes32(data[offset:offset + 32]));
            proof.commitmentRows[r].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // Evaluation proofs (decode ALL)
        uint256 numEvals = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        proof.podps = new HyraxVerifier.PODPProof[](numEvals);
        proof.comEvals = new HyraxVerifier.G1Point[](numEvals);

        for (uint256 e = 0; e < numEvals; e++) {
            offset = _decodePODP(data, offset, proof.podps[e]);
            proof.comEvals[e].x = uint256(bytes32(data[offset:offset + 32]));
            proof.comEvals[e].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        return offset;
    }

    /// @dev Decode public value claims from proof data at the given offset.
    /// @dev Each claim: value(32) + blinding(32) + commitment(64) + pointLen(32) + point[...](32 each)
    function _decodePublicValueClaims(bytes calldata data, uint256 offset)
        private
        pure
        returns (GKRDAGVerifier.PublicValueClaim[] memory claims)
    {
        uint256 numClaims = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        claims = new GKRDAGVerifier.PublicValueClaim[](numClaims);
        for (uint256 i = 0; i < numClaims; i++) {
            claims[i].value = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            claims[i].blinding = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            claims[i].commitment.x = uint256(bytes32(data[offset:offset + 32]));
            claims[i].commitment.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            // Skip point (not needed; we resolve points from circuit topology)
            uint256 numPoint = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numPoint * 32;
        }
    }

    /// @dev Skip a claim section in proof data
    function _skipClaim(bytes calldata data, uint256 offset) private pure returns (uint256) {
        offset += 32; // value
        offset += 32; // blinding
        offset += 64; // commitment point
        uint256 numPoint = uint256(bytes32(data[offset:offset + 32]));
        offset += 32 + numPoint * 32;
        return offset;
    }

    // ========================================================================
    // PEDERSEN GENERATORS DECODING
    // ========================================================================

    /// @notice Decode Pedersen generators from calldata bytes
    /// @dev Format: numMessageGens (uint256) | G1[numMessageGens] | G1(scalarGen) | G1(blindingGen)
    function decodePedersenGens(bytes calldata gensData)
        internal
        pure
        returns (HyraxVerifier.PedersenGens memory gens)
    {
        if (gensData.length == 0) {
            // Empty gens — PODP verification will fail if actually needed
            gens.messageGens = new HyraxVerifier.G1Point[](0);
            return gens;
        }

        uint256 offset = 0;

        // Number of message generators
        uint256 numGens = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;

        // Message generators (g_1..g_m)
        gens.messageGens = new HyraxVerifier.G1Point[](numGens);
        for (uint256 i = 0; i < numGens; i++) {
            gens.messageGens[i].x = uint256(bytes32(gensData[offset:offset + 32]));
            offset += 32;
            gens.messageGens[i].y = uint256(bytes32(gensData[offset:offset + 32]));
            offset += 32;
        }

        // Scalar generator (g_scalar)
        gens.scalarGen.x = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
        gens.scalarGen.y = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;

        // Blinding generator (h)
        gens.blindingGen.x = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
        gens.blindingGen.y = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
    }

    // ========================================================================
    // CIRCUIT MANAGEMENT
    // ========================================================================

    /// @notice Register a new circuit configuration
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param numLayers Number of GKR circuit layers
    /// @param layerSizes Size of each layer
    /// @param layerTypes Type of each layer (0=add, 1=mul, 2=const, 3=input)
    /// @param isCommitted Whether each layer has Hyrax commitment
    /// @param name Human-readable circuit name
    function registerCircuit(
        bytes32 circuitHash,
        uint256 numLayers,
        uint256[] calldata layerSizes,
        uint8[] calldata layerTypes,
        bool[] calldata isCommitted,
        string calldata name
    ) external onlyAdmin {
        _registerCircuit(circuitHash, numLayers, layerSizes, layerTypes, isCommitted, name, bytes32(0));
    }

    /// @notice Register a circuit with Pedersen generator hash validation
    /// @param gensHash keccak256 of the expected Pedersen generators calldata (0 = skip validation)
    function registerCircuitWithGens(
        bytes32 circuitHash,
        uint256 numLayers,
        uint256[] calldata layerSizes,
        uint8[] calldata layerTypes,
        bool[] calldata isCommitted,
        string calldata name,
        bytes32 gensHash
    ) external onlyAdmin {
        _registerCircuit(circuitHash, numLayers, layerSizes, layerTypes, isCommitted, name, gensHash);
    }

    function _registerCircuit(
        bytes32 circuitHash,
        uint256 numLayers,
        uint256[] calldata layerSizes,
        uint8[] calldata layerTypes,
        bool[] calldata isCommitted,
        string calldata name,
        bytes32 gensHash
    ) private {
        require(circuits[circuitHash].circuitHash == bytes32(0), "Circuit already registered");
        require(layerSizes.length == numLayers, "Layer sizes length mismatch");
        require(layerTypes.length == numLayers, "Layer types length mismatch");
        require(isCommitted.length == numLayers, "IsCommitted length mismatch");

        GKRVerifier.CircuitDescription memory desc = GKRVerifier.CircuitDescription({
            numLayers: numLayers, layerSizes: layerSizes, layerTypes: layerTypes, isCommitted: isCommitted
        });

        circuits[circuitHash] =
            CircuitConfig({circuitHash: circuitHash, description: desc, active: true, name: name, gensHash: gensHash});

        circuitHashes.push(circuitHash);

        emit CircuitRegistered(circuitHash, name);
    }

    /// @notice Deactivate a circuit
    function deactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = false;
        emit CircuitDeactivated(circuitHash);
    }

    /// @notice Reactivate a circuit
    function reactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = true;
    }

    /// @notice Transfer admin rights
    function transferAdmin(address newAdmin) external onlyAdmin {
        emit AdminTransferred(admin, newAdmin);
        admin = newAdmin;
    }

    /// @notice Set the Groth16 verifier contract address (for hybrid verification)
    function setGroth16Verifier(address _groth16Verifier) external onlyAdmin {
        groth16Verifier = _groth16Verifier;
    }

    /// @notice Set a per-circuit Groth16 verifier address and input count
    function setCircuitGroth16Verifier(bytes32 circuitHash, address verifier, uint256 groth16InputCount)
        external
        onlyAdmin
    {
        require(circuits[circuitHash].circuitHash != bytes32(0), "Circuit not registered");
        circuitGroth16Verifiers[circuitHash] = verifier;
        circuitGroth16Selectors[circuitHash] = _computeGroth16Selector(groth16InputCount);
    }

    // ========================================================================
    // DAG CIRCUIT REGISTRATION & VERIFICATION
    // ========================================================================

    /// @notice Register a DAG circuit
    /// @param circuitHash SHA-256 of circuit description
    /// @param descData ABI-encoded DAGCircuitDescription fields:
    ///        (uint256 numComputeLayers, uint256 numInputLayers, uint8[] layerTypes,
    ///         uint256[] numSumcheckRounds, uint256[] atomOffsets, uint256[] atomTargetLayers,
    ///         uint256[] ptOffsets, uint256[] ptData, bool[] inputIsCommitted)
    /// @param name Human-readable name
    /// @param gensHash keccak256 of expected generators (0 = skip)
    function registerDAGCircuit(
        bytes32 circuitHash,
        bytes calldata descData,
        string calldata name,
        bytes32 gensHash
    ) external onlyAdmin {
        require(dagCircuits[circuitHash].circuitHash == bytes32(0), "DAG circuit already registered");

        GKRDAGVerifier.DAGCircuitDescription memory desc = abi.decode(descData, (GKRDAGVerifier.DAGCircuitDescription));
        require(desc.layerTypes.length == desc.numComputeLayers, "layerTypes length mismatch");
        require(desc.atomOffsets.length == desc.numComputeLayers + 1, "atomOffsets length mismatch");

        dagCircuits[circuitHash] = DAGCircuitConfig({
            circuitHash: circuitHash,
            description: desc,
            active: true,
            name: name,
            gensHash: gensHash
        });

        circuitHashes.push(circuitHash);
        emit CircuitRegistered(circuitHash, name);
    }

    /// @notice Verify a DAG circuit proof (compute layers only — input layers verified separately)
    function verifyDAGProof(
        bytes calldata proof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData
    ) external view returns (bool valid) {
        DAGCircuitConfig storage config = dagCircuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        if (proof.length < 4) revert InvalidProofLength();
        if (bytes4(proof[:4]) != bytes4("REM1")) revert InvalidProofSelector();

        if (config.gensHash != bytes32(0) && gensData.length > 0) {
            if (keccak256(gensData) != config.gensHash) revert InvalidGenerators();
        }

        (
            GKRVerifier.GKRProof memory gkrProof,
            ,
            GKRDAGVerifier.DAGInputLayerProof[] memory dagInputProofs,
            GKRDAGVerifier.PublicValueClaim[] memory publicValueClaims
        ) = decodeProofForDAG(proof[4:], publicInputs);
        // Populate inputProofs with commitment rows for transcript setup
        gkrProof.inputProofs = new HyraxVerifier.EvalProof[](dagInputProofs.length);
        for (uint256 i = 0; i < dagInputProofs.length; i++) {
            gkrProof.inputProofs[i].commitmentRows = dagInputProofs[i].commitmentRows;
        }
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);
        // Use proof-embedded public inputs for both transcript AND MLE evaluation
        // (the embedded data is the actual public input layer table, which may differ from external publicInputs)
        uint256[] memory embeddedPubInputs = _decodeEmbeddedPublicInputs(proof[4:]);
        PoseidonSponge.Sponge memory sponge = _setupTranscript(circuitHash, embeddedPubInputs, gkrProof);

        // Verify compute layers (use embeddedPubInputs for MLE evaluation of public input layer)
        GKRDAGVerifier.VerifyContext memory ctx =
            GKRDAGVerifier.verifyComputeLayers(gkrProof, config.description, gens, sponge, embeddedPubInputs, dagInputProofs, publicValueClaims);

        // Verify input layers (committed + public)
        GKRDAGVerifier.verifyInputLayers(ctx, sponge);

        valid = true;
    }

    /// @notice Check if a DAG circuit is registered and active
    function isDAGCircuitActive(bytes32 circuitHash) external view returns (bool) {
        return dagCircuits[circuitHash].active;
    }

    // ========================================================================
    // VIEW FUNCTIONS
    // ========================================================================

    /// @notice Check if a circuit is registered and active
    function isCircuitActive(bytes32 circuitHash) external view returns (bool) {
        return circuits[circuitHash].active;
    }

    /// @notice Public wrapper for _hashToFqPair (for testing)
    function hashToFqPair(bytes32 hash) external pure returns (uint256 fq1, uint256 fq2) {
        return _hashToFqPair(hash);
    }

    /// @notice Public wrapper for _decodeEmbeddedPublicInputs (for testing)
    function decodeEmbeddedPublicInputsExternal(bytes calldata proofData)
        external
        pure
        returns (uint256[] memory)
    {
        return _decodeEmbeddedPublicInputs(proofData);
    }

    /// @notice Public wrapper for decodeProofForDAG (for testing)
    function decodeDAGInputProofCounts(bytes calldata proofData)
        external
        pure
        returns (uint256 numLayers, uint256[] memory numRows, uint256[] memory numEvals)
    {
        (,, GKRDAGVerifier.DAGInputLayerProof[] memory dagProofs,) = decodeProofForDAG(proofData, proofData[0:0]);
        numLayers = dagProofs.length;
        numRows = new uint256[](numLayers);
        numEvals = new uint256[](numLayers);
        for (uint256 i = 0; i < numLayers; i++) {
            numRows[i] = dagProofs[i].commitmentRows.length;
            numEvals[i] = dagProofs[i].podps.length;
        }
    }

    /// @notice Get all registered circuit hashes
    function getCircuitHashes() external view returns (bytes32[] memory) {
        return circuitHashes;
    }

    // ========================================================================
    // FIAT-SHAMIR TRANSCRIPT SETUP
    // ========================================================================

    /// @notice Set up the initial Fiat-Shamir transcript matching Remainder's ECTranscript protocol
    /// @dev Absorbs: circuit hash Fq pair (2) + public inputs (N) + pub hash chain (2) +
    ///      EC commitment points (M*2) + EC hash chain (2) = 6 + N + M*2 absorbs total
    /// @param circuitHash SHA3-256 hash of the circuit description
    /// @param pubInputs Decoded public input values
    /// @param gkrProof Decoded proof (for extracting EC commitment points from input proofs)
    /// @return sponge Initialized transcript ready for GKRVerifier
    function _setupTranscript(bytes32 circuitHash, uint256[] memory pubInputs, GKRVerifier.GKRProof memory gkrProof)
        internal
        view
        returns (PoseidonSponge.Sponge memory sponge)
    {
        sponge = PoseidonSponge.init();

        // 1. Absorb circuit hash as two Fq elements (16-byte halves, LE interpreted)
        (uint256 fq1, uint256 fq2) = _hashToFqPair(circuitHash);
        PoseidonSponge.absorbPair(sponge, fq1, fq2);

        // 2. Absorb public input values
        for (uint256 i = 0; i < pubInputs.length; i++) {
            PoseidonSponge.absorb(sponge, pubInputs[i]);
        }

        // 3. Absorb SHA-256 hash chain of public inputs
        (uint256 pubHash1, uint256 pubHash2) = _sha256HashChain(pubInputs);
        PoseidonSponge.absorbPair(sponge, pubHash1, pubHash2);

        // 4. Absorb EC commitment points from input proofs
        uint256[] memory ecCoords = _extractInputCommitCoords(gkrProof);
        for (uint256 i = 0; i < ecCoords.length; i += 2) {
            PoseidonSponge.absorbPair(sponge, ecCoords[i], ecCoords[i + 1]);
        }

        // 5. Absorb SHA-256 hash chain of EC commitment coordinates
        (uint256 ecHash1, uint256 ecHash2) = _sha256HashChain(ecCoords);
        PoseidonSponge.absorbPair(sponge, ecHash1, ecHash2);
    }

    /// @notice Extract all input commitment point coordinates from decoded proof
    /// @dev Returns [x0, y0, x1, y1, ...] for all commitment rows across all input proofs
    function _extractInputCommitCoords(GKRVerifier.GKRProof memory proof)
        internal
        pure
        returns (uint256[] memory coords)
    {
        // Count total coordinates
        uint256 total = 0;
        for (uint256 i = 0; i < proof.inputProofs.length; i++) {
            total += proof.inputProofs[i].commitmentRows.length * 2;
        }

        coords = new uint256[](total);
        uint256 idx = 0;
        for (uint256 i = 0; i < proof.inputProofs.length; i++) {
            for (uint256 j = 0; j < proof.inputProofs[i].commitmentRows.length; j++) {
                coords[idx++] = proof.inputProofs[i].commitmentRows[j].x;
                coords[idx++] = proof.inputProofs[i].commitmentRows[j].y;
            }
        }
    }

    /// @notice Convert a 32-byte hash into two Fq elements (each from a 16-byte half, LE interpreted)
    /// @dev Matches Remainder's circuit_hash_to_fq_pair: split at byte 16, each half padded to 32 LE bytes
    function _hashToFqPair(bytes32 hash) internal pure returns (uint256 fq1, uint256 fq2) {
        assembly {
            // First 16 bytes → LE uint256
            fq1 := 0
            for { let i := 0 } lt(i, 16) { i := add(i, 1) } { fq1 := or(shl(mul(i, 8), byte(i, hash)), fq1) }
            // Second 16 bytes → LE uint256
            fq2 := 0
            for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
                fq2 := or(shl(mul(i, 8), byte(add(i, 16), hash)), fq2)
            }
        }
    }

    /// @notice Compute 1000-iteration SHA-256 hash chain, split into two Fq elements
    /// @dev Matches Remainder's append_input_* hash chain:
    ///      1. Concatenate Fq elements as LE 32-byte arrays
    ///      2. SHA-256 of concatenation
    ///      3. Iterate SHA-256 1000 times
    ///      4. Split 32-byte result into two 16-byte halves → LE Fq
    function _sha256HashChain(uint256[] memory fqElements) internal view returns (uint256 fq1, uint256 fq2) {
        assembly {
            let count := mload(fqElements)
            let inputLen := mul(count, 32)

            // Use scratch space at free memory pointer for LE-encoded input
            let ptr := mload(0x40)

            // Convert each Fq element to 32-byte LE and write to ptr
            for { let i := 0 } lt(i, count) { i := add(i, 1) } {
                let val := mload(add(fqElements, mul(add(i, 1), 32)))
                // Byte-reverse uint256: swap bytes using O(log n) bitwise operations
                // Swap adjacent bytes (swap odd/even byte positions)
                val := or(
                    and(shr(8, val), 0x00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF),
                    and(shl(8, val), 0xFF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00FF00)
                )
                // Swap adjacent 2-byte groups
                val := or(
                    and(shr(16, val), 0x0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF),
                    and(shl(16, val), 0xFFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000FFFF0000)
                )
                // Swap adjacent 4-byte groups
                val := or(
                    and(shr(32, val), 0x00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF),
                    and(shl(32, val), 0xFFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000)
                )
                // Swap adjacent 8-byte groups
                val := or(
                    and(shr(64, val), 0x0000000000000000FFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFFF),
                    and(shl(64, val), 0xFFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFFF0000000000000000)
                )
                // Swap 16-byte halves
                val := or(shr(128, val), shl(128, val))
                mstore(add(ptr, mul(i, 32)), val)
            }

            // Initial SHA-256 via precompile 0x02: sha256(inputBytes)
            if iszero(staticcall(gas(), 0x02, ptr, inputLen, ptr, 32)) { revert(0, 0) }

            // 1000-iteration hash chain: reuse same 32-byte slot at ptr
            for { let k := 0 } lt(k, 1000) { k := add(k, 1) } {
                if iszero(staticcall(gas(), 0x02, ptr, 32, ptr, 32)) { revert(0, 0) }
            }

            // Read final 32-byte hash and split into two 16-byte LE Fq values
            let hash := mload(ptr)
            // First 16 bytes (high 128 bits of hash) → LE uint256
            fq1 := 0
            for { let j := 0 } lt(j, 16) { j := add(j, 1) } {
                fq1 := or(shl(mul(j, 8), byte(j, hash)), fq1)
            }
            // Second 16 bytes (low 128 bits of hash) → LE uint256
            fq2 := 0
            for { let j := 0 } lt(j, 16) { j := add(j, 1) } {
                fq2 := or(shl(mul(j, 8), byte(add(j, 16), hash)), fq2)
            }
        }
    }
}
