// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import {PoseidonSponge} from "./PoseidonSponge.sol";
import {SumcheckVerifier} from "./SumcheckVerifier.sol";
import {HyraxVerifier} from "./HyraxVerifier.sol";
import {GKRVerifier} from "./GKRVerifier.sol";
import {CommittedSumcheckVerifier} from "./CommittedSumcheckVerifier.sol";

/// @title RemainderVerifier
/// @notice Top-level on-chain verifier for Remainder (GKR+Hyrax) proofs
/// @dev Verifies proofs of ML inference generated by Remainder_CE.
///
///      Verification flow:
///      1. Decode ABI-encoded proof into GKR + Hyrax components
///      2. Replay Fiat-Shamir transcript (Poseidon sponge)
///      3. Verify GKR layer reductions (via SumcheckVerifier)
///      4. Verify Hyrax polynomial commitment openings
///      5. Return true if all checks pass
///
///      Each registered circuit has a fixed description hash that
///      identifies the model structure. The proof must reference
///      a registered circuit.
contract RemainderVerifier {
    // ========================================================================
    // TYPES
    // ========================================================================

    /// @notice Registered circuit configuration
    struct CircuitConfig {
        bytes32 circuitHash; // SHA-256 of circuit description
        GKRVerifier.CircuitDescription description;
        bool active;
        string name; // Human-readable name (e.g., "XGBoost-5feat-10trees")
    }

    // ========================================================================
    // STATE
    // ========================================================================

    /// @notice Admin address
    address public admin;

    /// @notice Registered circuits by hash
    mapping(bytes32 => CircuitConfig) public circuits;

    /// @notice List of registered circuit hashes
    bytes32[] public circuitHashes;

    // ========================================================================
    // EVENTS
    // ========================================================================

    event CircuitRegistered(bytes32 indexed circuitHash, string name);
    event CircuitDeactivated(bytes32 indexed circuitHash);
    event ProofVerified(bytes32 indexed circuitHash, bool valid);
    event AdminTransferred(address indexed oldAdmin, address indexed newAdmin);

    // ========================================================================
    // ERRORS
    // ========================================================================

    error NotAdmin();
    error CircuitNotRegistered();
    error CircuitNotActive();
    error InvalidProofSelector();
    error InvalidProofLength();
    error ProofVerificationFailed();

    // ========================================================================
    // MODIFIERS
    // ========================================================================

    modifier onlyAdmin() {
        if (msg.sender != admin) revert NotAdmin();
        _;
    }

    // ========================================================================
    // CONSTRUCTOR
    // ========================================================================

    constructor(address _admin) {
        admin = _admin;
    }

    // ========================================================================
    // VERIFICATION
    // ========================================================================

    /// @notice Verify a Remainder proof
    /// @param proof ABI-encoded proof data (starts with "REM1" selector)
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param publicInputs Public input values
    /// @param gensData ABI-encoded Pedersen generators for PODP verification
    /// @return valid Whether the proof is valid
    function verifyProof(
        bytes calldata proof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData
    ) external returns (bool valid) {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Decode the proof and generators
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);

        // Verify GKR proof
        valid = GKRVerifier.verify(gkrProof, config.description, pubInputs, gens);

        emit ProofVerified(circuitHash, valid);
    }

    /// @notice Verify a proof (reverts on invalid proof — for use by ExecutionEngine)
    /// @param proof ABI-encoded proof data
    /// @param circuitHash Circuit identifier
    /// @param publicInputs Public input values
    /// @param gensData ABI-encoded Pedersen generators for PODP verification
    function verifyOrRevert(
        bytes calldata proof,
        bytes32 circuitHash,
        bytes calldata publicInputs,
        bytes calldata gensData
    ) external view {
        // Check circuit is registered and active
        CircuitConfig storage config = circuits[circuitHash];
        if (config.circuitHash == bytes32(0)) revert CircuitNotRegistered();
        if (!config.active) revert CircuitNotActive();

        // Check proof selector
        if (proof.length < 4) revert InvalidProofLength();
        bytes4 selector = bytes4(proof[:4]);
        if (selector != bytes4("REM1")) revert InvalidProofSelector();

        // Decode and verify
        (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs) = decodeProof(proof[4:], publicInputs);
        HyraxVerifier.PedersenGens memory gens = decodePedersenGens(gensData);

        bool valid = GKRVerifier.verify(gkrProof, config.description, pubInputs, gens);
        if (!valid) revert ProofVerificationFailed();
    }

    // ========================================================================
    // PROOF DECODING
    // ========================================================================

    /// @notice Decode ABI-encoded proof bytes into committed GKR proof structure
    /// @param proofData Proof data (after selector)
    /// @param publicInputBytes Raw public input bytes
    /// @return gkrProof Decoded GKR proof (committed sumcheck format)
    /// @return pubInputs Decoded public inputs as field elements
    function decodeProof(bytes calldata proofData, bytes calldata publicInputBytes)
        internal
        pure
        returns (GKRVerifier.GKRProof memory gkrProof, uint256[] memory pubInputs)
    {
        uint256 offset = 0;

        // Skip circuit hash (32 bytes)
        offset += 32;

        // Skip public inputs section (decoded separately from publicInputBytes)
        uint256 numPubInputSections = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numPubInputSections; i++) {
            uint256 cnt = uint256(bytes32(proofData[offset:offset + 32]));
            offset += 32 + cnt * 32;
        }

        // Skip output layer proofs (G1 points)
        uint256 numOutputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        // Save output values (extract from proof)
        gkrProof.outputValues = new uint256[](0); // Output values come from public inputs
        offset += numOutputProofs * 64;

        // Decode committed layer proofs
        uint256 numLayerProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        gkrProof.layerProofs = new GKRVerifier.CommittedLayerProof[](numLayerProofs);

        for (uint256 i = 0; i < numLayerProofs; i++) {
            offset = _decodeCommittedLayerProof(proofData, offset, gkrProof.layerProofs[i]);
        }

        // Skip Fiat-Shamir claims section
        uint256 numFsClaims = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numFsClaims; i++) {
            offset = _skipClaim(proofData, offset);
        }

        // Skip public value claims section
        uint256 numPubClaims = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        for (uint256 i = 0; i < numPubClaims; i++) {
            offset = _skipClaim(proofData, offset);
        }

        // Decode Hyrax input proofs (with PODP data)
        uint256 numInputProofs = uint256(bytes32(proofData[offset:offset + 32]));
        offset += 32;
        gkrProof.inputProofs = new HyraxVerifier.EvalProof[](numInputProofs);

        for (uint256 i = 0; i < numInputProofs; i++) {
            offset = _decodeInputProof(proofData, offset, gkrProof.inputProofs[i]);
        }

        // Decode public inputs from separate calldata
        uint256 numPubInputs = publicInputBytes.length / 32;
        pubInputs = new uint256[](numPubInputs);
        for (uint256 i = 0; i < numPubInputs; i++) {
            pubInputs[i] = uint256(bytes32(publicInputBytes[i * 32:(i + 1) * 32]));
        }
    }

    /// @dev Decode a single committed layer proof from proof bytes
    function _decodeCommittedLayerProof(
        bytes calldata data,
        uint256 offset,
        GKRVerifier.CommittedLayerProof memory layerProof
    ) private pure returns (uint256) {
        // ProofOfSumcheck: sum (G1)
        layerProof.sumcheckProof.sum.x = uint256(bytes32(data[offset:offset + 32]));
        layerProof.sumcheckProof.sum.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        // ProofOfSumcheck: messages (G1[])
        uint256 numMessages = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.sumcheckProof.messages = new HyraxVerifier.G1Point[](numMessages);
        for (uint256 j = 0; j < numMessages; j++) {
            layerProof.sumcheckProof.messages[j].x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.sumcheckProof.messages[j].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // ProofOfSumcheck: PODP
        offset = _decodePODP(data, offset, layerProof.sumcheckProof.podp);

        // Post-sumcheck commitments (G1[])
        uint256 numCommits = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.commitments = new HyraxVerifier.G1Point[](numCommits);
        for (uint256 j = 0; j < numCommits; j++) {
            layerProof.commitments[j].x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.commitments[j].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // ProofOfProduct entries
        uint256 numPops = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        layerProof.pops = new HyraxVerifier.ProofOfProduct[](numPops);
        for (uint256 j = 0; j < numPops; j++) {
            // 3 G1 points: alpha, beta, delta
            layerProof.pops[j].alpha.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].alpha.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            layerProof.pops[j].beta.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].beta.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            layerProof.pops[j].delta.x = uint256(bytes32(data[offset:offset + 32]));
            layerProof.pops[j].delta.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
            // 5 scalars: z1..z5
            layerProof.pops[j].z1 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z2 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z3 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z4 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
            layerProof.pops[j].z5 = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
        }

        // Skip claim aggregation (optional)
        uint256 hasAgg = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        if (hasAgg == 1) {
            // Skip coefficients
            uint256 numCoeffs = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numCoeffs * 64;
            // Skip openings
            uint256 numOpenings = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numOpenings * (64 + 64);
            // Skip equality proofs
            uint256 numEq = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + numEq * (64 + 32);
        }

        return offset;
    }

    /// @dev Decode a PODP proof from proof bytes
    function _decodePODP(bytes calldata data, uint256 offset, HyraxVerifier.PODPProof memory podp)
        private
        pure
        returns (uint256)
    {
        podp.commitD.x = uint256(bytes32(data[offset:offset + 32]));
        podp.commitD.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        podp.commitDDotA.x = uint256(bytes32(data[offset:offset + 32]));
        podp.commitDDotA.y = uint256(bytes32(data[offset + 32:offset + 64]));
        offset += 64;

        uint256 numZ = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        podp.zVector = new uint256[](numZ);
        for (uint256 i = 0; i < numZ; i++) {
            podp.zVector[i] = uint256(bytes32(data[offset:offset + 32]));
            offset += 32;
        }

        podp.zDelta = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        podp.zBeta = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;

        return offset;
    }

    /// @dev Decode a Hyrax input proof (commitment rows + PODP + comEval)
    function _decodeInputProof(bytes calldata data, uint256 offset, HyraxVerifier.EvalProof memory proof)
        private
        pure
        returns (uint256)
    {
        // Commitment rows
        uint256 numRows = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;
        proof.commitmentRows = new HyraxVerifier.G1Point[](numRows);
        for (uint256 r = 0; r < numRows; r++) {
            proof.commitmentRows[r].x = uint256(bytes32(data[offset:offset + 32]));
            proof.commitmentRows[r].y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // Evaluation proofs
        uint256 numEvals = uint256(bytes32(data[offset:offset + 32]));
        offset += 32;

        if (numEvals > 0) {
            offset = _decodePODP(data, offset, proof.podp);
            // commitmentToEvaluation
            proof.comEval.x = uint256(bytes32(data[offset:offset + 32]));
            proof.comEval.y = uint256(bytes32(data[offset + 32:offset + 64]));
            offset += 64;
        }

        // Skip additional eval proofs
        for (uint256 e = 1; e < numEvals; e++) {
            offset += 128; // commitD + commitDDotA
            uint256 skipZ = uint256(bytes32(data[offset:offset + 32]));
            offset += 32 + skipZ * 32 + 64; // z_vector + z_delta + z_beta
            offset += 64; // comEval
        }

        return offset;
    }

    /// @dev Skip a claim section in proof data
    function _skipClaim(bytes calldata data, uint256 offset) private pure returns (uint256) {
        offset += 32; // value
        offset += 32; // blinding
        offset += 64; // commitment point
        uint256 numPoint = uint256(bytes32(data[offset:offset + 32]));
        offset += 32 + numPoint * 32;
        return offset;
    }

    // ========================================================================
    // PEDERSEN GENERATORS DECODING
    // ========================================================================

    /// @notice Decode Pedersen generators from calldata bytes
    /// @dev Format: numMessageGens (uint256) | G1[numMessageGens] | G1(scalarGen) | G1(blindingGen)
    function decodePedersenGens(bytes calldata gensData)
        internal
        pure
        returns (HyraxVerifier.PedersenGens memory gens)
    {
        if (gensData.length == 0) {
            // Empty gens — PODP verification will fail if actually needed
            gens.messageGens = new HyraxVerifier.G1Point[](0);
            return gens;
        }

        uint256 offset = 0;

        // Number of message generators
        uint256 numGens = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;

        // Message generators (g_1..g_m)
        gens.messageGens = new HyraxVerifier.G1Point[](numGens);
        for (uint256 i = 0; i < numGens; i++) {
            gens.messageGens[i].x = uint256(bytes32(gensData[offset:offset + 32]));
            offset += 32;
            gens.messageGens[i].y = uint256(bytes32(gensData[offset:offset + 32]));
            offset += 32;
        }

        // Scalar generator (g_scalar)
        gens.scalarGen.x = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
        gens.scalarGen.y = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;

        // Blinding generator (h)
        gens.blindingGen.x = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
        gens.blindingGen.y = uint256(bytes32(gensData[offset:offset + 32]));
        offset += 32;
    }

    // ========================================================================
    // CIRCUIT MANAGEMENT
    // ========================================================================

    /// @notice Register a new circuit configuration
    /// @param circuitHash SHA-256 hash of the circuit description
    /// @param numLayers Number of GKR circuit layers
    /// @param layerSizes Size of each layer
    /// @param layerTypes Type of each layer (0=add, 1=mul, 2=const, 3=input)
    /// @param isCommitted Whether each layer has Hyrax commitment
    /// @param name Human-readable circuit name
    function registerCircuit(
        bytes32 circuitHash,
        uint256 numLayers,
        uint256[] calldata layerSizes,
        uint8[] calldata layerTypes,
        bool[] calldata isCommitted,
        string calldata name
    ) external onlyAdmin {
        require(circuits[circuitHash].circuitHash == bytes32(0), "Circuit already registered");
        require(layerSizes.length == numLayers, "Layer sizes length mismatch");
        require(layerTypes.length == numLayers, "Layer types length mismatch");
        require(isCommitted.length == numLayers, "IsCommitted length mismatch");

        GKRVerifier.CircuitDescription memory desc = GKRVerifier.CircuitDescription({
            numLayers: numLayers, layerSizes: layerSizes, layerTypes: layerTypes, isCommitted: isCommitted
        });

        circuits[circuitHash] = CircuitConfig({circuitHash: circuitHash, description: desc, active: true, name: name});

        circuitHashes.push(circuitHash);

        emit CircuitRegistered(circuitHash, name);
    }

    /// @notice Deactivate a circuit
    function deactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = false;
        emit CircuitDeactivated(circuitHash);
    }

    /// @notice Reactivate a circuit
    function reactivateCircuit(bytes32 circuitHash) external onlyAdmin {
        if (circuits[circuitHash].circuitHash == bytes32(0)) revert CircuitNotRegistered();
        circuits[circuitHash].active = true;
    }

    /// @notice Transfer admin rights
    function transferAdmin(address newAdmin) external onlyAdmin {
        emit AdminTransferred(admin, newAdmin);
        admin = newAdmin;
    }

    // ========================================================================
    // VIEW FUNCTIONS
    // ========================================================================

    /// @notice Check if a circuit is registered and active
    function isCircuitActive(bytes32 circuitHash) external view returns (bool) {
        return circuits[circuitHash].active;
    }

    /// @notice Get all registered circuit hashes
    function getCircuitHashes() external view returns (bytes32[] memory) {
        return circuitHashes;
    }
}
